### ISSUE TITLE
ReferenceError in /todo

### ISSUE THREAD

**Issue by btarr** [btarr/dev-ops-bugsnag-demo#10]
## Error in Swen 559

**ReferenceError** in **/todo**
text is not defined

[View on Bugsnag](https://app.bugsnag.com/rit/swen-559/errors/5cb5f117597aaa00183f7f47?event_id=5cb5f1170037e0d5a3310000&i=gh&m=ci)

## Stacktrace

    webpack-internal:///./src/components/todo/ToDoPage.jsx:67 - ToDoPage.handleDeleteTodo

[View full stacktrace](https://app.bugsnag.com/rit/swen-559/errors/5cb5f117597aaa00183f7f47?event_id=5cb5f1170037e0d5a3310000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by steplica** [comment]
Team 6 claimed

**Comment by smcintosh881** [comment]
Full stack trace
```
ReferenceError text is not defined 
    webpack-internal:///./src/components/todo/ToDoPage.jsx:67:27 ToDoPage.handleDeleteTodo
    webpack-internal:///./src/components/todo/ToDoPage.jsx:92:25 Object.onClick
    webpack-internal:///./node_modules/lodash/_apply.js:15:25 apply
    webpack-internal:///./node_modules/lodash/_baseInvoke.js:21:37 baseInvoke
    webpack-internal:///./node_modules/lodash/_apply.js:16:25 apply
    webpack-internal:///./node_modules/lodash/_overRest.js:32:12 eval
    webpack-internal:///./node_modules/semantic-ui-react/dist/es/elements/Button/Button.js:109:59 eval
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:149:14 HTMLUnknownElement.callCallback
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:199:16 Object.invokeGuardedCallbackDev
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:256:31 invokeGuardedCallback
```

**Comment by btarr** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ReferenceError** in **/todo**](https://app.bugsnag.com/rit/swen-559/errors/5cb5f117597aaa00183f7f47?event_id=5cb5f64e0037f4d9841c0000&i=gh&m=fx)
