### ISSUE TITLE
Error in /testt

### ISSUE THREAD

**Issue by btarr** [btarr/dev-ops-bugsnag-demo#12]
## Error in Swen 559

**Error** in **/testt**
user hit invalid route, check to see that route doesn't have a typo

[View on Bugsnag](https://app.bugsnag.com/rit/swen-559/errors/5cb5f1299c8f97001972a939?event_id=5cb5f1290037f08f32e30000&i=gh&m=ci)

## Stacktrace

    webpack-internal:///./src/App.jsx:47 - NoMatch

[View full stacktrace](https://app.bugsnag.com/rit/swen-559/errors/5cb5f1299c8f97001972a939?event_id=5cb5f1290037f08f32e30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by DanudeSandstorm** [comment]
4 claim

**Comment by btarr** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **/testt**](https://app.bugsnag.com/rit/swen-559/errors/5cb5f1299c8f97001972a939?event_id=5cb5f89f0037e66ff0040000&i=gh&m=fx)
