### ISSUE TITLE
ReferenceError in /

### ISSUE THREAD

**Issue by btarr** [btarr/dev-ops-bugsnag-demo#25]
## Error in Swen 559

**ReferenceError** in **/**
SpotfyPlayer is not defined

[View on Bugsnag](https://app.bugsnag.com/rit/swen-559/errors/5cb5f256e10e330019c9589f?event_id=5cb5f2560037e0d6ab080000&i=gh&m=ci)

## Stacktrace

    webpack-internal:///./src/components/home/FeaturedContent.jsx:94 - FeaturedContent.renderFeaturedSong

[View full stacktrace](https://app.bugsnag.com/rit/swen-559/errors/5cb5f256e10e330019c9589f?event_id=5cb5f2560037e0d6ab080000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by scioffi** [comment]
.

**Comment by smcintosh881** [comment]
Full stack trace
```
ReferenceError SpotfyPlayer is not defined 
    webpack-internal:///./src/components/home/FeaturedContent.jsx:94:145 FeaturedContent.renderFeaturedSong
    webpack-internal:///./src/components/home/FeaturedContent.jsx:149:23 FeaturedContent.renderFeaturedContent
    webpack-internal:///./src/components/home/FeaturedContent.jsx:160:15 FeaturedContent.render
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14741:31 finishClassComponent
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14696:24 updateClassComponent
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15644:16 beginWork
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19312:12 performUnitOfWork
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19352:24 workLoop
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:149:14 HTMLUnknownElement.callCallback
    webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:199:16 Object.invokeGuardedCallbackDev
```

**Comment by btarr** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ReferenceError** in **/**](https://app.bugsnag.com/rit/swen-559/errors/5cb5f256e10e330019c9589f?event_id=5cb5f3f20037e4fb6be80000&i=gh&m=fx)
